---
title: "4Data_1day_it_other"
author: "Guirong Fu"
date: "April 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(dplyr)
library(glmnet)
library(xgboost)
library(Matrix)
#library(DiagrammeR)
#install.packages("DiagrammeR")
#install.packages("xgboost")
```

## Lasso


```{r}
path_s<-paste0(getwd(),"/data/Nodes/features/")
files_s<-dir(path_s)
it = read.csv(paste0(path_s,files_s[14]),stringsAsFactors = F)
target = read.csv(paste0(getwd(),"/data/0415TweetsStatistics.csv"))
data = it[18:nrow(it),2:ncol(it)] # 2.8
y=target$it # 02.09
if(length(y)>nrow(data)){
  y = y[1:nrow(data)]
}
ttl_len = length(y)
test_len = floor(ttl_len*0.3)

data <- as.matrix(data)
X_sd<-scale(data)

X_train = X_sd[1:(ttl_len-test_len),]
y_train = y[1:(ttl_len-test_len)]
X_test = X_sd[(ttl_len-test_len+1):ttl_len,]
y_test = y[(ttl_len-test_len+1):ttl_len]

fit1<-cv.glmnet(X_train,y_train,type.measure = "mse",family="gaussian")
plot(fit1)
plot(fit1$glmnet.fit)
```

```{r}
fit1_coef<-coef(fit1,s=fit1$lambda.1se)
fit1_coef
y_pred<-predict(fit1,X_test) 
```

```{r}
X_id = which(fit1_coef!=0)
X_act = colnames(X_train)[X_id]
X_act
pvalue=rep(0,ncol(X_train))
cors = rep(0,ncol(X_train))
for(i in 1:ncol(X_train)){
  sumry = cor.test(X_train[,i],y_train)
  pvalue[i]=sumry$p.value
  cors[i]=sumry$estimate
}
X_id2 = which(pvalue<0.05)
X_act2 = colnames(X_train)[X_id2]
X_act2

print("Correlation: individual")
cors[X_id2]
fit1_coef[X_id]
```

```{r compare}
lm1<-lm(y_train~X_train[,X_id])
summary(lm1)
lm2<-lm(y_train~X_train[,X_id2])
summary(lm2)
```
```{r compare-predict}
X = data.frame(X_test[,X_id])
y1<-predict(lm1,X)
y2<-predict(lm2,X)

lm3<-lm(y_train~X_train[,c("confirm","DeathR")])
summary(lm3)
y3<-predict(lm3,X)
```

## XGBoost

```{r}
train_data = xgb.DMatrix(data = X_train, label = y_train) 
xgb <- xgboost(data = train_data,max_depth=6, eta=0.5,  objective='reg:squarederror', nround=50, verbose = 0)
test_data=xgb.DMatrix(data=X_test,label=y_test)
y_xgb = predict(xgb, test_data)

cv <- xgb.cv(data =  X_train, label = y_train,nrounds = 10, nthread = 2, nfold = 5, 
       max_depth = 5, eta = 0.3,objective='reg:squarederror',verbose = 0)
print(cv, verbose=TRUE)
```


```{r analyse}

plot(y_test,type="l",ylim=c(0,120000))
lines(y_xgb,col=2)
xgb.plot.importance(xgb.importance(model=xgb))
#xgb.plot.shap(X_test, model=xgb)
xgb.plot.multi.trees(xgb)
```
```{r}

plot(y_test,type="l",ylim=c(0,150000))
lines(y1,col="aliceblue")
lines(y2,col="azure2")
lines(y3,col="chocolate1")
lines(y_pred,col="cyan3")
lines(y_xgb,col="gold")

mse0 = sqrt(mean((y_test-y_pred)^2))
mse1 = sqrt(mean((y_test-y1)^2))
mse2 = sqrt(mean((y_test-y2)^2))
mse3 = sqrt(mean((y_test-y3)^2))
mse4 = sqrt(mean((y_test-y_xgb)^2))
mse_df = data.frame(x = c(mse0,mse1,mse2,mse3,mse4), row.names = c("Lasso","LM:lasso1","LM:cor","LM:lasso2","XGboost") )
barplot(mse_df$x,names.arg  = rownames(mse_df))
```

