---
title: "4Strength Twitter"
author: "Guirong Fu"
date: "April 19, 2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(dplyr)
library(glmnet)
library(xgboost)
library(Matrix)
library(stringr)
source("./lib/utils.R")
```

```{r, include=F}

date_start = 18 # 2.8
date_end = 90 # 4.20

```

## Read data

```{r, include=FALSE}
path_s<-paste0(getwd(),"/data/Nodes/features/")
files_s<-dir(path_s)
it = read.csv(paste0(path_s,"It.csv"),stringsAsFactors = F)
hi = read.csv(paste0(path_s,"Hi.csv"),stringsAsFactors = F)
ja = read.csv(paste0(path_s,"Ja.csv"),stringsAsFactors = F)
ko = read.csv(paste0(path_s,"Ko.csv"),stringsAsFactors = F)
ru = read.csv(paste0(path_s,"Ru.csv"),stringsAsFactors = F)
de = read.csv(paste0(path_s,"De.csv"),stringsAsFactors = F)

short_paths<-read.csv(paste0(getwd(),"/data/Nodes/shortest_path.csv"))
target = read.csv(paste0(getwd(),"/data/0421TweetsStatistics.csv"))
```

# Correlations

## Autocorrelation

```{r}
it_ar = cor.test(target$it[2:nrow(target)],target$it[1:(nrow(target)-1)])
hi_ar = cor.test(target$hi[2:nrow(target)],target$hi[1:(nrow(target)-1)])
de_ar = cor.test(target$de[2:nrow(target)],target$de[1:(nrow(target)-1)])
ja_ar = cor.test(target$ja[2:nrow(target)],target$ja[1:(nrow(target)-1)])
ko_ar = cor.test(target$ko[2:nrow(target)],target$ko[1:(nrow(target)-1)])
ru_ar = cor.test(target$ru[2:nrow(target)],target$ru[1:(nrow(target)-1)])


plot_dat_ar = data.frame(cor= c(it_ar$estimate, hi_ar$estimate, de_ar$estimate, ja_ar$estimate, ko_ar$estimate, ru_ar$estimate),
                      name = c("it","hi","de","ja","ko","ru"), stringsAsFactors = F)

#ggplot(plot_dat_ar,aes(name))+geom_bar(stat=cor)
barplot(plot_dat_ar$cor,names.arg=plot_dat_ar$name)
```

## Confirm 

### Itself

```{r, include=FALSE}
x_de = de$confirm[date_start:date_end]
y_de = target$de # 2.9 - 4.21
cor_de = cor.test(x_de,y_de)
#cor.test(y_de,de$confirm[date_start:date_end])
#cor.test(y_de[2:length(y_de)],y_de[1:(length(y_de)-1)])

x_it = it$confirm[date_start:date_end]
y_it = target$it
cor_it = cor.test(x_it,y_it)

x_hi = hi$confirm[date_start:date_end]
y_hi = target$hi
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$confirm[date_start:date_end]
y_ja = target$ja
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$confirm[date_start:date_end]
y_ko = target$ko
cor_ko = cor.test(x_ko,y_ko)


x_ru = ru$confirm[date_start:date_end]
y_ru = target$ru
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_cf = cor_report_0
write.csv(cor_report_0,file="./data/results/Confirm_twitter_self.csv")

```

### Neighbors

```{r, include=FALSE}
dat_other_it_1<-GetNeighData("It",short_paths,1,files_s,path_s,date_start,date_end)
cor_it = cor.test(dat_other_it_1$confirm,y_it)

dat_other_hi_1<-GetNeighData("Hi",short_paths,1,files_s,path_s,date_start,date_end)
cor_hi = cor.test(dat_other_hi_1$confirm,y_hi)

dat_other_ja_1<-GetNeighData("Ja",short_paths,1,files_s,path_s,date_start,date_end)
cor_ja = cor.test(dat_other_ja_1$confirm,y_ja)

dat_other_ko_1<-GetNeighData("Ko",short_paths,1,files_s,path_s,date_start,date_end)
cor_ko = cor.test(dat_other_ko_1$confirm,y_ko)

dat_other_de_1<-GetNeighData("De",short_paths,1,files_s,path_s,date_start,date_end)
cor_de = cor.test(dat_other_de_1$confirm,y_de)

dat_other_ru_1<-GetNeighData("Ru",short_paths,1,files_s,path_s,date_start,date_end)
cor_ru = cor.test(dat_other_ru_1$confirm,y_ru)




cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_1
write.csv(cor_report_1,file="./data/results/Confirm_twitter_neighbour1.csv")

```

```{r, include=FALSE}
dat_other_it_2<-GetNeighData("It",short_paths,2,files_s,path_s,date_start,date_end)
cor_it = cor.test(dat_other_it_2$confirm,y_it)

dat_other_hi_2<-GetNeighData("Hi",short_paths,2,files_s,path_s,date_start,date_end)
cor_hi = cor.test(dat_other_hi_2$confirm,y_hi)

dat_other_ja_2<-GetNeighData("Ja",short_paths,2,files_s,path_s,date_start,date_end)
cor_ja = cor.test(dat_other_ja_2$confirm,y_ja)

dat_other_ko_2<-GetNeighData("Ko",short_paths,2,files_s,path_s,date_start,date_end)
cor_ko = cor.test(dat_other_ko_2$confirm,y_ko)

dat_other_de_2<-GetNeighData("De",short_paths,2,files_s,path_s,date_start,date_end)
cor_de = cor.test(dat_other_de_2$confirm, y_de)

dat_other_ru_2<-GetNeighData("Ru",short_paths,2,files_s,path_s,date_start,date_end)
cor_ru = cor.test(dat_other_ru_2$confirm,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        name = c("de","hi","it","ja","ko","ru"),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
cor_report_2
write.csv(cor_report_2,file="./data/results/Confirm_twitter_neighbour2.csv")

```

### Report
```{r}
library(ggplot2)
plot_dat_conf = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_conf,aes(x=type,y = cor))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Confirm: Estimated Correlation")
#+ geom_ribbon(aes(ymin = lower, ymax=upper,group=name), alpha = 0.2) 

ggplot(plot_dat_conf,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```


## Confirm daily

### Itself

```{r, include=F}
x_de = de$confirm_daily[date_start:date_end]
y_de = target$de
cor_de = cor.test(x_de,y_de)
#cor.test(y_de,de$confirm[date_start:date_end])
#cor.test(y_de[2:length(y_de)],y_de[1:(length(y_de)-1)])

x_it = it$confirm_daily[date_start:date_end]
y_it = target$it
cor_it = cor.test(x_it,y_it)

x_hi = hi$confirm_daily[date_start:date_end]
y_hi = target$hi
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$confirm_daily[date_start:date_end]
y_ja = target$ja
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$confirm_daily[date_start:date_end]
y_ko = target$ko
cor_ko = cor.test(x_ko,y_ko)


x_ru = ru$confirm_daily[date_start:date_end]
y_ru = target$ru
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_cfd = cor_report_0
write.csv(cor_report_0,file="./data/results/Confirm_daily_twitter_self.csv")

```

### Neighbors

```{r, include=FALSE}

cor_it = cor.test(dat_other_it_1$confirm_daily,y_it)
cor_hi = cor.test(dat_other_hi_1$confirm_daily,y_hi)
cor_ja = cor.test(dat_other_ja_1$confirm_daily,y_ja)
cor_ko = cor.test(dat_other_ko_1$confirm_daily,y_ko)
cor_de = cor.test(dat_other_de_1$confirm_daily,y_de)
cor_ru = cor.test(dat_other_ru_1$confirm_daily,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_1
write.csv(cor_report_1,file="./data/results/Confirm_daily_twitter_neighbour1.csv")

```

```{r, include=F}
cor_it = cor.test(dat_other_it_2$confirm_daily,y_it)
cor_hi = cor.test(dat_other_hi_2$confirm_daily,y_hi)
cor_ja = cor.test(dat_other_ja_2$confirm_daily,y_ja)
cor_ko = cor.test(dat_other_ko_2$confirm_daily,y_ko)
cor_de = cor.test(dat_other_de_2$confirm_daily,y_de)
cor_ru = cor.test(dat_other_ru_2$confirm_daily,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
cor_report_2
write.csv(cor_report_2,file="./data/results/Confirm_daily_twitter_neighbour2.csv")

```

### Report
```{r}
library(ggplot2)
plot_dat_conf_daily = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name),
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_conf_daily,aes(x=type,y = cor))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))#+geom_ribbon(aes(ymin=lower,ymax=upper,group=name),alpha=.2)

ggplot(plot_dat_conf_daily,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```

## Death 

### Itself

```{r, include=F}
x_de = de$death[date_start:date_end]
cor_de = cor.test(x_de,y_de)

x_it = it$death[date_start:date_end]
cor_it = cor.test(x_it,y_it)

x_hi = hi$death[date_start:date_end]
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$death[date_start:date_end]
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$death[date_start:date_end]
cor_ko = cor.test(x_ko,y_ko)


x_ru = ru$death[date_start:date_end]
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_d = cor_report_0
write.csv(cor_report_0,file="./data/results/Death_twitter_self.csv")

```

### Neighbors

```{r, include=F}
cor_it = cor.test(dat_other_it_1$death,y_it)
cor_hi = cor.test(dat_other_hi_1$death,y_hi)
cor_ja = cor.test(dat_other_ja_1$death,y_ja)
cor_ko = cor.test(dat_other_ko_1$death,y_ko)
cor_de = cor.test(dat_other_de_1$death,y_de)
cor_ru = cor.test(dat_other_ru_1$death,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_1
write.csv(cor_report_1,file="./data/results/Death_twitter_neighbour1.csv")

```

```{r, include=F}
cor_it = cor.test(dat_other_it_2$death,y_it)
cor_hi = cor.test(dat_other_hi_2$death,y_hi)
cor_ja = cor.test(dat_other_ja_2$death,y_ja)
cor_ko = cor.test(dat_other_ko_2$death,y_ko)
cor_de = cor.test(dat_other_de_2$death, y_de)
cor_ru = cor.test(dat_other_ru_2$death,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
cor_report_2
write.csv(cor_report_2,file="./data/results/Death_twitter_neighbour2.csv")

```

### Report
```{r}
library(ggplot2)
plot_dat_death = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name), 
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_death,aes(x=type,y = cor))+geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name))+ggtitle("Death")#+ geom_ribbon(aes(ymin = lower,group=name, ymax=upper),alpha=.2)


ggplot(plot_dat_death,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```


## Death Daily

```{r, include=F}
### Itself

x_de = de$death_daily[date_start:date_end]
cor_de = cor.test(x_de,y_de)

x_it = it$death_daily[date_start:date_end]
cor_it = cor.test(x_it,y_it)

x_hi = hi$death_daily[date_start:date_end]
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$death_daily[date_start:date_end]
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$death_daily[date_start:date_end]
cor_ko = cor.test(x_ko,y_ko)


x_ru = ru$death_daily[date_start:date_end]
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_dd = cor_report_0
write.csv(cor_report_0,file="./data/results/Death_daily_twitter_self.csv")



### Neighbors
cor_it = cor.test(dat_other_it_1$death_daily,y_it)
cor_hi = cor.test(dat_other_hi_1$death_daily,y_hi)
cor_ja = cor.test(dat_other_ja_1$death_daily,y_ja)
cor_ko = cor.test(dat_other_ko_1$death_daily,y_ko)
cor_de = cor.test(dat_other_de_1$death_daily,y_de)
cor_ru = cor.test(dat_other_ru_1$death_daily,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
#cor_report_1
write.csv(cor_report_1,file="./data/results/Death_daily_twitter_neighbour1.csv")

cor_it = cor.test(dat_other_it_2$death_daily,y_it)
cor_hi = cor.test(dat_other_hi_2$death_daily,y_hi)
cor_ja = cor.test(dat_other_ja_2$death_daily,y_ja)
cor_ko = cor.test(dat_other_ko_2$death_daily,y_ko)
cor_de = cor.test(dat_other_de_2$death_daily, y_de)
cor_ru = cor.test(dat_other_ru_2$death_daily,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
#cor_report_2
write.csv(cor_report_2,file="./data/results/Death_daily_twitter_neighbour2.csv")

```

### Report
```{r, echo=F}
library(ggplot2)
plot_dat_death_daily = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name), 
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_death_daily,aes(x=type,y = cor))+ geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name))+ggtitle("Death Daily") #+ geom_ribbon(aes(ymin = lower,group=name, ymax=upper),alpha=.2)


ggplot(plot_dat_death_daily,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```

## ConfDR

```{r, include=F}
### Itself
x_de = de$ConfDR[date_start:date_end]
cor_de = cor.test(x_de,y_de)

x_it = it$ConfDR[date_start:date_end]
cor_it = cor.test(x_it,y_it)

x_hi = hi$ConfDR[date_start:date_end]
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$ConfDR[date_start:date_end]
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$ConfDR[date_start:date_end]
cor_ko = cor.test(x_ko,y_ko)

x_ru = ru$ConfDR[date_start:date_end]
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_cdr = cor_report_0
write.csv(cor_report_0,file="./data/results/ConfDR_twitter_self.csv")

### Neighbours

cor_it = cor.test(dat_other_it_1$ConfDR,y_it)
cor_hi = cor.test(dat_other_hi_1$ConfDR,y_hi)
cor_ja = cor.test(dat_other_ja_1$ConfDR,y_ja)
cor_ko = cor.test(dat_other_ko_1$ConfDR,y_ko)
cor_de = cor.test(dat_other_de_1$ConfDR,y_de)
cor_ru = cor.test(dat_other_ru_1$ConfDR,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
#cor_report_1
write.csv(cor_report_1,file="./data/results/ConfDR_twitter_neighbour1.csv")

cor_it = cor.test(dat_other_it_2$ConfDR,y_it)
cor_hi = cor.test(dat_other_hi_2$ConfDR,y_hi)
cor_ja = cor.test(dat_other_ja_2$ConfDR,y_ja)
cor_ko = cor.test(dat_other_ko_2$ConfDR,y_ko)
cor_de = cor.test(dat_other_de_2$ConfDR, y_de)
cor_ru = cor.test(dat_other_ru_2$ConfDR,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
#cor_report_2
write.csv(cor_report_2,file="./data/results/ConfDR_twitter_neighbour2.csv")

```
### Report
```{r, echo=F}
library(ggplot2)
plot_dat_confdr = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name), 
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_confdr,aes(x=type,y = cor))+ geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name)) #+ geom_ribbon(aes(ymin = lower,group=name, ymax=upper),alpha=.2)


ggplot(plot_dat_confdr,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```

## DeathR

```{r, include=F}

### Itself

x_de = de$DeathR[date_start:date_end]
cor_de = cor.test(x_de,y_de)

x_it = it$DeathR[date_start:date_end]
cor_it = cor.test(x_it,y_it)

x_hi = hi$DeathR[date_start:date_end]
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$DeathR[date_start:date_end]
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$DeathR[date_start:date_end]
cor_ko = cor.test(x_ko,y_ko)

x_ru = ru$DeathR[date_start:date_end]
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_dr = cor_report_0
write.csv(cor_report_0,file="./data/results/DeathR_twitter_self.csv")

### Neighbours
cor_it = cor.test(dat_other_it_1$DeathR,y_it)
cor_hi = cor.test(dat_other_hi_1$DeathR,y_hi)
cor_ja = cor.test(dat_other_ja_1$DeathR,y_ja)
cor_ko = cor.test(dat_other_ko_1$DeathR,y_ko)
cor_de = cor.test(dat_other_de_1$DeathR,y_de)
cor_ru = cor.test(dat_other_ru_1$DeathR,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
#cor_report_1
write.csv(cor_report_1,file="./data/results/DeathR_twitter_neighbour1.csv")

cor_it = cor.test(dat_other_it_2$DeathR,y_it)
cor_hi = cor.test(dat_other_hi_2$DeathR,y_hi)
cor_ja = cor.test(dat_other_ja_2$DeathR,y_ja)
cor_ko = cor.test(dat_other_ko_2$DeathR,y_ko)
cor_de = cor.test(dat_other_de_2$DeathR, y_de)
cor_ru = cor.test(dat_other_ru_2$DeathR,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
#cor_report_2
write.csv(cor_report_2,file="./data/results/DeathR_twitter_neighbour2.csv")

```
### Report
```{r, echo=F}
library(ggplot2)
plot_dat_deathr = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name), 
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_deathr,aes(x=type,y = cor))+ geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name)) #+ geom_ribbon(aes(ymin = lower,group=name, ymax=upper),alpha=.2)


ggplot(plot_dat_deathr,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```

## Recover

```{r, include=F}

### Itself

x_de = de$recover[date_start:date_end]
cor_de = cor.test(x_de,y_de)

x_it = it$recover[date_start:date_end]
cor_it = cor.test(x_it,y_it)

x_hi = hi$recover[date_start:date_end]
cor_hi = cor.test(x_hi,y_hi)

x_ja = ja$recover[date_start:date_end]
cor_ja = cor.test(x_ja,y_ja)

x_ko = ko$recover[date_start:date_end]
cor_ko = cor.test(x_ko,y_ko)

x_ru = ru$recover[date_start:date_end]
cor_ru = cor.test(x_ru,y_ru)

cor_report_0 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
cor_report_rec = cor_report_0
write.csv(cor_report_0,file="./data/results/Recover_twitter_self.csv")

### Neighbours
cor_it = cor.test(dat_other_it_1$recover,y_it)
cor_hi = cor.test(dat_other_hi_1$recover,y_hi)
cor_ja = cor.test(dat_other_ja_1$recover,y_ja)
cor_ko = cor.test(dat_other_ko_1$recover,y_ko)
cor_de = cor.test(dat_other_de_1$recover,y_de)
cor_ru = cor.test(dat_other_ru_1$recover,y_ru)


cor_report_1 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value),stringsAsFactors = F)
#cor_report_1
write.csv(cor_report_1,file="./data/results/Recover_twitter_neighbour1.csv")

cor_it = cor.test(dat_other_it_2$recover,y_it)
cor_hi = cor.test(dat_other_hi_2$recover,y_hi)
cor_ja = cor.test(dat_other_ja_2$recover,y_ja)
cor_ko = cor.test(dat_other_ko_2$recover,y_ko)
cor_de = cor.test(dat_other_de_2$recover, y_de)
cor_ru = cor.test(dat_other_ru_2$recover,y_ru)


cor_report_2 = data.frame(cor = c(cor_de$estimate,cor_hi$estimate, cor_it$estimate,cor_ja$estimate, cor_ko$estimate, cor_ru$estimate), 
                        name = c("de","hi","it","ja","ko","ru"), 
                        low = c(cor_de$conf.int[1],cor_hi$conf.int[1], cor_it$conf.int[1], cor_ja$conf.int[1], cor_ko$conf.int[1], cor_ru$conf.int[1]),
                        up = c(cor_de$conf.int[2], cor_hi$conf.int[2], cor_it$conf.int[2], cor_ja$conf.int[2], cor_ko$conf.int[2],cor_ru$conf.int[2]),
                        pvalue = c(cor_de$p.value,cor_hi$p.value, cor_it$p.value,cor_ja$p.value, cor_ko$p.value,cor_ru$p.value), stringsAsFactors = F)
#cor_report_2
write.csv(cor_report_2,file="./data/results/Recover_twitter_neighbour2.csv")

```
### Report
```{r, echo=F}
library(ggplot2)
plot_dat_rec = data.frame(cor= c(cor_report_0$cor,cor_report_1$cor,cor_report_2$cor),
                      name = c(cor_report_0$name,cor_report_1$name,cor_report_2$name), 
                      lower = c(cor_report_0$low, cor_report_1$low, cor_report_2$low),
                      upper = c(cor_report_0$up, cor_report_1$up, cor_report_2$up),
                      pvalue = c(cor_report_0$pvalue,cor_report_1$pvalue,cor_report_2$pvalue),
                      type = c(rep("0-step Self",6),rep("1-step Neigh",6),rep("2-step Neigh",6)),stringsAsFactors = F)

ggplot(plot_dat_rec,aes(x=type,y = cor))+ geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name))+ggtitle("Recover") #+ geom_ribbon(aes(ymin = lower,group=name, ymax=upper),alpha=.2)


ggplot(plot_dat_rec,aes(x=type,y = pvalue))+geom_line(aes(group=name,colour=name))+geom_point(aes(colour=name))+ggtitle("Cor Test P-value")
```


## Overall

```{r}

plot_dat<-data.frame(cor = c(cor_report_cf$cor,cor_report_cfd$cor,cor_report_d$cor,cor_report_dd$cor,cor_report_cdr$cor,cor_report_dr$cor,cor_report_rec$cor),
                     pvalue = c(cor_report_cf$pvalue,cor_report_cfd$pvalue,cor_report_d$pvalue,cor_report_dd$pvalue,cor_report_cdr$pvalue,cor_report_dr$pvalue,cor_report_rec$pvalue),
                       name = c(cor_report_cf$name,cor_report_cfd$name,cor_report_d$name,cor_report_dd$name,cor_report_cdr$name,cor_report_dr$name,cor_report_rec$name),
                       type = c(rep("Confirm",6),rep("Confirm_daily",6),rep("Death",6),rep("Death_daily",6),rep("ConfDR",6),rep("DeathR",6),rep("Recover",6)))

ggplot(plot_dat,aes(x=type,y = cor)) + geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name))
ggplot(plot_dat,aes(x=type,y = pvalue)) + geom_line(aes(group=name,colour=name))+ geom_point(aes(colour=name))

```



